// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightLossApp.Api.Data;

#nullable disable

namespace WeightLossApp.Api.Migrations
{
    [DbContext(typeof(WeightLossDbContext))]
    partial class WeightLossDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WeightLossApp.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaloriesPerServing")
                        .HasColumnType("int");

                    b.Property<int>("CarbsPerServing")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeEaten")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProteinPerServing")
                        .HasColumnType("int");

                    b.Property<double>("Servings")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Kellogs",
                            CaloriesPerServing = 140,
                            CarbsPerServing = 34,
                            CreatedAt = new DateTime(2022, 4, 7, 13, 12, 36, 797, DateTimeKind.Local).AddTicks(7511),
                            DateTimeEaten = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Frosted Flakes",
                            ProteinPerServing = 2,
                            Servings = 2.0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Monster Energy",
                            CaloriesPerServing = 10,
                            CarbsPerServing = 3,
                            CreatedAt = new DateTime(2022, 4, 7, 13, 12, 36, 797, DateTimeKind.Local).AddTicks(7561),
                            DateTimeEaten = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ultra Paradise",
                            ProteinPerServing = 0,
                            Servings = 1.0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "JJ's Bakery",
                            CaloriesPerServing = 390,
                            CarbsPerServing = 59,
                            CreatedAt = new DateTime(2022, 4, 7, 13, 12, 36, 797, DateTimeKind.Local).AddTicks(7569),
                            DateTimeEaten = new DateTime(2022, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lightly Glazed Apple Pie",
                            ProteinPerServing = 3,
                            Servings = 1.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
